Repository Daniel-Yonkov/jest-mysql, pull requests merged in 2020-11, with the labels that each got.

#28 Add port parameter to mysql DB load
  __tests__/environment/mysqlConfigParameters.js
  __tests__/setupHooks/loadSetupHooks.js
  databaseSetup.js
  default-config.js
  package.json
  tests/configs/default.js
  tests/configs/providedSchema.js
  tests/configs/truncateEnabled.js
Labels: enhancement

#29 Version 1.1.0
  .github/workflows/build.yml
  .github/workflows/npmpublish.yml
  __tests__/environment/mysqlConfigParameters.js
  __tests__/setupHooks/emptyHookFile.js
  __tests__/setupHooks/loadSetupHooks.js
  databaseSetup.js
  default-config.js
  package.json
  tests/configs/default.js
  tests/configs/providedSchema.js
  tests/configs/truncateEnabled.js
Labels: Release

#30 Update package version
  package.json
Labels: Hotfix, Release
